platform:
  security:
    enabled: ${SECURITY_ENABLED:true}
  datasource:
    writer:
      url: ${DB_WRITER_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    reader:
      url: ${DB_READER_URL:}
      username: ${DB_READER_USERNAME:${DB_USERNAME}}
      password: ${DB_READER_PASSWORD:${DB_PASSWORD}}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}
